wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1722848778
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.13
      5: 0.17.0
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
